/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RecoveryCodeRouteImport } from './routes/recovery-code'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardAdvisorRouteImport } from './routes/dashboard_.advisor'
import { Route as DashboardMyProjectsRouteImport } from './routes/dashboard_.my-projects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard_.profile'
import { Route as DashboardUploadRouteImport } from './routes/dashboard_.upload'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'
import { Route as ApiAdvisorStreamRouteImport } from './routes/api/advisor/stream'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProjectsProjectIdDocumentRouteImport } from './routes/api/projects/$projectId/document'
import { Route as ApiProjectsProjectIdPagesPageNumberRouteImport } from './routes/api/projects/$projectId/pages/$pageNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryCodeRoute = RecoveryCodeRouteImport.update({
  id: '/recovery-code',
  path: '/recovery-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdvisorRoute = DashboardAdvisorRouteImport.update({
  id: '/dashboard_/advisor',
  path: '/dashboard/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyProjectsRoute = DashboardMyProjectsRouteImport.update({
  id: '/dashboard_/my-projects',
  path: '/dashboard/my-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard_/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/dashboard_/upload',
  path: '/dashboard/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorStreamRoute = ApiAdvisorStreamRouteImport.update({
  id: '/api/advisor/stream',
  path: '/api/advisor/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdDocumentRoute =
  ApiProjectsProjectIdDocumentRouteImport.update({
    id: '/api/projects/$projectId/document',
    path: '/api/projects/$projectId/document',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdPagesPageNumberRoute =
  ApiProjectsProjectIdPagesPageNumberRouteImport.update({
    id: '/api/projects/$projectId/pages/$pageNumber',
    path: '/api/projects/$projectId/pages/$pageNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/projects': typeof ProjectsRoute
  '/recovery-code': typeof RecoveryCodeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/my-projects': typeof DashboardMyProjectsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/advisor/stream': typeof ApiAdvisorStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/$projectId/document': typeof ApiProjectsProjectIdDocumentRoute
  '/api/projects/$projectId/pages/$pageNumber': typeof ApiProjectsProjectIdPagesPageNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/projects': typeof ProjectsRoute
  '/recovery-code': typeof RecoveryCodeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/my-projects': typeof DashboardMyProjectsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/advisor/stream': typeof ApiAdvisorStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/$projectId/document': typeof ApiProjectsProjectIdDocumentRoute
  '/api/projects/$projectId/pages/$pageNumber': typeof ApiProjectsProjectIdPagesPageNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/projects': typeof ProjectsRoute
  '/recovery-code': typeof RecoveryCodeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard_/advisor': typeof DashboardAdvisorRoute
  '/dashboard_/my-projects': typeof DashboardMyProjectsRoute
  '/dashboard_/profile': typeof DashboardProfileRoute
  '/dashboard_/upload': typeof DashboardUploadRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/api/advisor/stream': typeof ApiAdvisorStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/$projectId/document': typeof ApiProjectsProjectIdDocumentRoute
  '/api/projects/$projectId/pages/$pageNumber': typeof ApiProjectsProjectIdPagesPageNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/projects'
    | '/recovery-code'
    | '/signin'
    | '/signup'
    | '/dashboard/advisor'
    | '/dashboard/my-projects'
    | '/dashboard/profile'
    | '/dashboard/upload'
    | '/projects/$projectId'
    | '/api/advisor/stream'
    | '/api/auth/$'
    | '/api/projects/$projectId/document'
    | '/api/projects/$projectId/pages/$pageNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/projects'
    | '/recovery-code'
    | '/signin'
    | '/signup'
    | '/dashboard/advisor'
    | '/dashboard/my-projects'
    | '/dashboard/profile'
    | '/dashboard/upload'
    | '/projects/$projectId'
    | '/api/advisor/stream'
    | '/api/auth/$'
    | '/api/projects/$projectId/document'
    | '/api/projects/$projectId/pages/$pageNumber'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/projects'
    | '/recovery-code'
    | '/signin'
    | '/signup'
    | '/dashboard_/advisor'
    | '/dashboard_/my-projects'
    | '/dashboard_/profile'
    | '/dashboard_/upload'
    | '/projects_/$projectId'
    | '/api/advisor/stream'
    | '/api/auth/$'
    | '/api/projects/$projectId/document'
    | '/api/projects/$projectId/pages/$pageNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProjectsRoute: typeof ProjectsRoute
  RecoveryCodeRoute: typeof RecoveryCodeRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardAdvisorRoute: typeof DashboardAdvisorRoute
  DashboardMyProjectsRoute: typeof DashboardMyProjectsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ApiAdvisorStreamRoute: typeof ApiAdvisorStreamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProjectsProjectIdDocumentRoute: typeof ApiProjectsProjectIdDocumentRoute
  ApiProjectsProjectIdPagesPageNumberRoute: typeof ApiProjectsProjectIdPagesPageNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-code': {
      id: '/recovery-code'
      path: '/recovery-code'
      fullPath: '/recovery-code'
      preLoaderRoute: typeof RecoveryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/advisor': {
      id: '/dashboard_/advisor'
      path: '/dashboard/advisor'
      fullPath: '/dashboard/advisor'
      preLoaderRoute: typeof DashboardAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/my-projects': {
      id: '/dashboard_/my-projects'
      path: '/dashboard/my-projects'
      fullPath: '/dashboard/my-projects'
      preLoaderRoute: typeof DashboardMyProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/profile': {
      id: '/dashboard_/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/upload': {
      id: '/dashboard_/upload'
      path: '/dashboard/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor/stream': {
      id: '/api/advisor/stream'
      path: '/api/advisor/stream'
      fullPath: '/api/advisor/stream'
      preLoaderRoute: typeof ApiAdvisorStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/document': {
      id: '/api/projects/$projectId/document'
      path: '/api/projects/$projectId/document'
      fullPath: '/api/projects/$projectId/document'
      preLoaderRoute: typeof ApiProjectsProjectIdDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/pages/$pageNumber': {
      id: '/api/projects/$projectId/pages/$pageNumber'
      path: '/api/projects/$projectId/pages/$pageNumber'
      fullPath: '/api/projects/$projectId/pages/$pageNumber'
      preLoaderRoute: typeof ApiProjectsProjectIdPagesPageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProjectsRoute: ProjectsRoute,
  RecoveryCodeRoute: RecoveryCodeRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardAdvisorRoute: DashboardAdvisorRoute,
  DashboardMyProjectsRoute: DashboardMyProjectsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ApiAdvisorStreamRoute: ApiAdvisorStreamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProjectsProjectIdDocumentRoute: ApiProjectsProjectIdDocumentRoute,
  ApiProjectsProjectIdPagesPageNumberRoute:
    ApiProjectsProjectIdPagesPageNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
